### ISSUE TITLE
Offset with three operand typo mistake

### ISSUE THREAD

**Issue by pedrociarlini** [lucyamy/LapX9C10X#1]
```
void LapX9C10X::offset(int value) {
  int v;
  v = _counterValue + value;
  **v = v < 0 : 0 : v;**
  _setValue(v);
}
```
Hello, in head branch this problem is fixed, but on tag 1.0.1(https://github.com/lucyamy/LapX9C10X/blob/1.0.1/src/LapX9C10X.cpp) the problem occurs.

**Comment by lucyamy** [comment]
I think I've worked out what I did wrong with the release. **Should** be fixed in V1.0.2.
Thank you very much for bringing that to my attention. My apologies.
