### ISSUE TITLE
#defines WRONG !!! in examples - STOPS LIB WORKING with the X9C10X IC

### ISSUE THREAD

**Issue by ftlpilot** [lucyamy/LapX9C10X#2]
The examples CLEARLY STATE in comments that the mapping is :- 
IC 1 - !INC - pin 5 (it's actually mapped to 6)
IC 2 - U/!D - pin 6 (it's actually mapped to 7)
IC 7 - !CS   - pin 7 (it's actually mapped to 5)
it would also be a good idea to EXPLICITELY MENTION that the Arduino pins are DIGITAL (D5/D6/D7)

However the ***CODE*** doesn't match, and I just wasted a couple of hours chasing this annoying bug - pity, it's a nice lib otherwise.

The actual code mapping is :-
#define CSPIN  5
#define INCPIN 6
#define UDPIN  7
 
This is clearly a typo/snafu/stuffup - BUT - without hours debugging - makes this library as useful as a brick (and even less useful if you are building a house).

**Comment by lucyamy** [comment]
Fixed comment
